[theme]
primaryColor = "#F97316"   # Naranja Fuego (Reemplaza al azul en botones/inputs)
backgroundColor = "#0F172A" # Fondo Azul Marino Profundo (El de tu imagen)
secondaryBackgroundColor = "#1E293B" # Fondo de la Barra Lateral y Tarjetas
textColor = "#F8FAFC"       # Texto Blanco Hielo
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false