# .streamlit/secrets.toml

[api_keys]
openweather = "60cbd579b9479b534ed3cd261e91bd9b"
nasa_firms = "49510555e9a70b9a7c8ac71d1d01087a"

[app_config]
# Coordenadas base de Ciudad Ju√°rez
lat_default = 31.6904
lon_default = -106.4245